/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

// Base Register addresses
#define RCC_BASE 0x40023800
#define GPIOA_BASE 0x40020000
#define TIM2_BASE 0x40000000
#define SYST_BASE 0xE000E010
#define ADC_BASE 0x40012000

// Central Clocking Register Addresses
#define RCC_AHB1ENR  (*(volatile uint32_t *)(RCC_BASE + 0x30))
#define RCC_APB1ENR  (*(volatile uint32_t *)(RCC_BASE + 0x40))
#define RCC_APB2ENR  (*(volatile uint32_t *)(RCC_BASE + 0x44))

// GPIOA Addresses (LED2 pin and analogue input pin)
#define GPIOA_MODER (*(volatile uint32_t *)(GPIOA_BASE + 0x00))
#define GPIOA_AFRL (*(volatile uint32_t *)(GPIOA_BASE + 0x20))
#define GPIOA_ODR  (*(volatile uint32_t *)(GPIOA_BASE + 0x14))

// Timer peripheral addresses
#define TIM2_CR1 (*(volatile uint32_t *)(TIM2_BASE + 0x00))
#define TIM2_CCMR1 (*(volatile uint32_t *)(TIM2_BASE + 0x18))
#define TIM2_CCER (*(volatile uint32_t *)(TIM2_BASE + 0x20))
#define TIM2_CNT (*(volatile uint32_t *)(TIM2_BASE + 0x24))
#define TIM2_PSC (*(volatile uint32_t *)(TIM2_BASE + 0x28))
#define TIM2_ARR (*(volatile uint32_t *)(TIM2_BASE + 0x2C))
#define TIM2_CCR1 (*(volatile uint32_t *)(TIM2_BASE + 0x34))

// ADC Addresses
#define ADC_SR (*(volatile uint32_t *)(ADC_BASE + 0x00)) // EOC bit
#define ADC_CR2 (*(volatile uint32_t *)(ADC_BASE + 0x08)) // start conversion, on/off
#define ADC_SQR1 (*(volatile uint32_t *)(ADC_BASE + 0x2C)) //conversion length
#define ADC_SQR3 (*(volatile uint32_t *)(ADC_BASE + 0x34)) //conversion sequence
#define ADC_DR (*(volatile uint32_t *)(ADC_BASE + 0x4C))

int main(void)
{
	// Enable clocks to GPIOA, TIM2, and ADC
	RCC_AHB1ENR |= (1 << 0);
	RCC_APB1ENR |= (1 << 0);
	RCC_APB2ENR |= (1 << 8);

	// Configure GPIOA Mode and setting Alternate Function (led)
	GPIOA_MODER &= ~(3 << 10);
	GPIOA_MODER |= (2 << 10);
	GPIOA_AFRL &= ~(15 << 20);
	GPIOA_AFRL |= (1 << 20);

	// Configure GPIOA Mode for ADC input (PA0)
	GPIOA_MODER |= (3 << 0);

	// Set PWM mode and output channel to 1
	TIM2_CCMR1 &= ~(7 << 4);
	TIM2_CCMR1 |= (6 << 4);
	TIM2_CCMR1 |= (1 << 3);

	// Set TIM2 frequency and clear counter
	TIM2_PSC = 15; //set as 16
	TIM2_ARR = 999; // set as 10^3
	TIM2_CNT = 0;
	TIM2_CCR1 = 0;

	// Configure ADC registers
	ADC_SQR1 &= ~(15 << 20);
	ADC_SQR3 &= ~(31 << 0);

	// Enable TIM2 and Channel 1 output, and ADC
	TIM2_CR1 |= (1 << 0);
	TIM2_CCER |= (1 << 0);
	ADC_CR2 |= (1 << 0);

	// Start first ADC conversion
	ADC_CR2 |= (1 << 30);
    /* Loop forever */
	for(;;) {
		if ((2 & ADC_SR) == 2) {
			uint32_t ADCOUT = ADC_DR & 4095;
			TIM2_CCR1 = 999 * ADCOUT / 4095;
			ADC_CR2 |= (1 << 30);
		}
	}
}
