/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

// Base Register addresses
#define RCC_BASE 0x40023800
#define GPIOA_BASE 0x40020000
#define GPIOB_BASE 0x40020400
#define USART2_BASE 0x40004400
#define I2C1_BASE 0x40005400

// Define register addresses
#define RCC_APB1ENR  (*(volatile uint32_t *)(RCC_BASE + 0x40))
#define RCC_AHB1ENR (*(volatile uint32_t *)(RCC_BASE + 0x30))
#define USART2_SR (*(volatile uint32_t *)(USART2_BASE + 0x00))
#define USART2_DR (*(volatile uint32_t *)(USART2_BASE + 0x04))
#define USART2_BRR (*(volatile uint32_t *)(USART2_BASE + 0x08))
#define USART2_CR1 (*(volatile uint32_t *)(USART2_BASE + 0x0C))
#define USART2_CR2 (*(volatile uint32_t *)(USART2_BASE + 0x10))
#define GPIOA_MODER (*(volatile uint32_t *)(GPIOA_BASE + 0x00))
#define GPIOA_AFRL (*(volatile uint32_t *)(GPIOA_BASE + 0x20)) //AF7
#define GPIOB_MODER (*(volatile uint32_t *)(GPIOB_BASE + 0x00))
#define GPIOB_OTYPER (*(volatile uint32_t *)(GPIOB_BASE + 0x04))
#define GPIOB_AFRH (*(volatile uint32_t *)(GPIOB_BASE + 0x24)) //AF4 on PB8 and PB9
#define I2C1_CR1 (*(volatile uint32_t *)(I2C1_BASE + 0x00))
#define I2C1_CR2 (*(volatile uint32_t *)(I2C1_BASE + 0x04))
#define I2C1_DR (*(volatile uint32_t *)(I2C1_BASE + 0x10))
#define I2C1_SR1 (*(volatile uint32_t *)(I2C1_BASE + 0x14))
#define I2C1_SR2 (*(volatile uint32_t *)(I2C1_BASE + 0x18))
#define I2C1_CCR (*(volatile uint32_t *)(I2C1_BASE + 0x1C))
#define I2C1_TRISE (*(volatile uint32_t *)(I2C1_BASE + 0x20))
#define I2C1_FLTR (*(volatile uint32_t *)(I2C1_BASE + 0x24))

int main(void)
{
// Enable clocks to USART2, GPIOA, GPIOB, IC21
	RCC_APB1ENR |= (1 << 17);
	RCC_APB1ENR |= (1 << 21);
	RCC_AHB1ENR |= (1 << 0);
	RCC_AHB1ENR |= (1 << 1);

	// Configure mode for GPIOA
	GPIOA_MODER &= ~(15 << 4);
	GPIOA_MODER |= (10 << 4);
	GPIOA_AFRL &= ~(255 << 8);
	GPIOA_AFRL |= (119 << 8);

	// Configure mode for GPIOB
	GPIOB_MODER &= ~(3 << 16);
	GPIOB_MODER |=  (2 << 16);
	GPIOB_MODER &= ~(3 << 18);
	GPIOB_MODER |=  (2 << 18);
	GPIOB_OTYPER |= (1 << 8);
	GPIOB_OTYPER |= (1 << 9);
	GPIOB_AFRH &= ~(15);
	GPIOB_AFRH |= (1 << 2);
	GPIOB_AFRH &= ~(15 << 4);
	GPIOB_AFRH |= (1 << 6);

	// Configure USART2 Registers
	USART2_BRR = (8 << 4) | 11;
	USART2_CR1 &= ~(1 << 12);
	USART2_CR1 |= (1 << 2);
	USART2_CR1 |= (1 << 3);
	USART2_CR1 &= ~(1 << 10);
	USART2_CR2 &= ~(3 << 12);

	// Configure I2C1 registers
	I2C1_CR2 |= 42; //set I2C1's internal clock to 42Mhz
	I2C1_CCR |= 210; // set I2C clock line frequency to 100khz
	I2C1_TRISE |= 43;

	// Enable peripherals
	I2C1_CR1 |= (1 << 0);
	USART2_CR1 |= (1 << 13);

	// Wake up MPU6050

	// Issue start
	I2C1_CR1 |= (1 << 8);

	// Check start flag
	while (!(I2C1_SR1 & 1));

	// Send slave address and WRITE MODE
	I2C1_DR = ((0x68 << 1) | 0);

	// Check address flag and clear it
	while (!(I2C1_SR1 & (1 << 1)));
	(void) I2C1_SR1;
	(void) I2C1_SR2;

	// Point the MPU6050 to its memory 0x6B to configure wake up settings
	I2C1_DR = 0x6B;

	// Check byte has been send out
	while (!(I2C1_SR1 & (1 << 7)));

	// Send out wake up call to MPU6050
	I2C1_DR = 0x01;

	// Check that byte has been sent out and we got an acknowledge back
	while (!(I2C1_SR1 & (1 << 2)));

	// Issue stop
	I2C1_CR1 |= (1 << 9);

	// Start reading data from MPU6050

	// Issue start and check start flags
	I2C1_CR1 |= (1 << 8);
	while (!(I2C1_SR1 & 1));

	// Send slave address and WRITE mode
	I2C1_DR = ((0x68 << 1) | 0);

	// check for address acknowledge and clear address flags
	while (!(I2C1_SR1 & (1 << 1)));
	(void) I2C1_SR1;
	(void) I2C1_SR2;

	// point MCU6050 to its sanity checker register position
	I2C1_DR = 0x75;

	// check byte has been send out
	while (!(I2C1_SR1 & (1 << 2)));

	// Issue repeated start to enter READ mode and check start flag
	I2C1_CR1 |= (1 << 8);
	while (!(I2C1_SR1 & 1));

	// Send slave address and READ mode
	I2C1_DR = ((0x68 << 1) | 1);

	// check address flag...
	while (!(I2C1_SR1 & (1 << 1)));

	//disable ACK because we are only reading 1 byte
	I2C1_CR1 &= ~ (1 << 10);

	//clear address flag
	(void) I2C1_SR1;
	(void) I2C1_SR2;

	// issue stop before we read so we don't read one more byte
	I2C1_CR1 |= (1 << 9);

	// make sure byte has arrived and read it
	while (!(I2C1_SR1 & (1 << 6)));
	uint8_t who_am_i = I2C1_DR;

	// Send over USART
	while (!(USART2_SR & (1 << 7)));
	USART2_DR = who_am_i;


    /* Loop forever */
	for(;;);

	//read orientation data from MPU6050 via I2C and do some math and transmit via UART to PC. print values every few seconds
}
