/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

// Register addresses
#define RCC_BASE    0x40023800
#define GPIOA_BASE  0x40020000
#define SYSCFG_BASE 0x40013800
#define TIM2_BASE 0x40000000
#define SYST_BASE 0xE000E010

#define RCC_AHB1ENR  (*(volatile uint32_t *)(RCC_BASE + 0x30))
#define RCC_APB1ENR  (*(volatile uint32_t *)(RCC_BASE + 0x40))
#define GPIOA_MODER (*(volatile uint32_t *)(GPIOA_BASE + 0x00))
#define GPIOA_AFRL (*(volatile uint32_t *)(GPIOA_BASE + 0x20))
#define TIM2_CR1 (*(volatile uint32_t *)(TIM2_BASE + 0x00))
#define TIM2_CCMR1 (*(volatile uint32_t *)(TIM2_BASE + 0x18))
#define TIM2_CCER (*(volatile uint32_t *)(TIM2_BASE + 0x20))
#define TIM2_CNT (*(volatile uint32_t *)(TIM2_BASE + 0x24))
#define TIM2_PSC (*(volatile uint32_t *)(TIM2_BASE + 0x28))
#define TIM2_ARR (*(volatile uint32_t *)(TIM2_BASE + 0x2C))
#define TIM2_CCR1 (*(volatile uint32_t *)(TIM2_BASE + 0x34))
#define SYST_CSR (*(volatile uint32_t *)(SYST_BASE + 0x00))
#define SYST_RVR (*(volatile uint32_t *)(SYST_BASE + 0x04))
#define SYST_CVR (*(volatile uint32_t *)(SYST_BASE + 0x08))

volatile uint32_t tick = 0;
volatile uint8_t update_flag = 0;
volatile uint8_t up = 1;

void SysTick_Handler(void) {
    tick++;
    update_flag = 1;  // signal main loop
}


int main(void)
{
	// Enable clocks to GPIOA and TIM2
	RCC_AHB1ENR |= (1 << 0);
	RCC_APB1ENR |= (1 << 0);

	// Configure GPIOA Mode and setting Alternate Function
	GPIOA_MODER &= ~(3 << 10);
	GPIOA_MODER |= (2 << 10);
	GPIOA_AFRL &= ~(15 << 20);
	GPIOA_AFRL |= (1 << 20);

	// Set PWM mode and output channel to 1
	TIM2_CCMR1 &= ~(7 << 4);
	TIM2_CCMR1 |= (6 << 4);
	TIM2_CCMR1 |= (1 << 3);

	// Enable Channel 1 output
	TIM2_CCER |= (1 << 0);

	// Set TIM2 frequency and clear counter
	TIM2_PSC = 15; //set as 16
	TIM2_ARR = 999; // set as 10^3
	TIM2_CNT = 0;
	TIM2_CCR1 = 0;

	// Configure SysTick and clear counter
	SYST_RVR = 159999;
	SYST_CVR = 0;

	// Enable TIM2 and SysTick
	SYST_CSR |= (1 << 0) | (1 << 1) | (1 << 2);
	TIM2_CR1 |= (1 << 0);

    /* Loop forever */
	for(;;) {
	    if (update_flag) {
	        update_flag = 0;
	        if (up) {
	            if (TIM2_CCR1 + 10 >= 999) {
	                TIM2_CCR1 = 999;
	                up = 0;
	            } else {
	                TIM2_CCR1 += 10;
	            }
	        } else {
	            if (TIM2_CCR1 <= 10) {
	                TIM2_CCR1 = 0;
	                up = 1;
	            } else {
	                TIM2_CCR1 -= 10;
	            }
	        }
	    }
	}
}
