/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

// Register addresses
#define RCC_BASE    0x40023800
#define GPIOA_BASE  0x40020000
#define GPIOC_BASE 0x40020800
#define SYSCFG_BASE 0x40013800
#define EXTI_BASE 0x40013C00

#define RCC_AHB1ENR  (*(volatile uint32_t *)(RCC_BASE + 0x30))
#define RCC_APB2ENR  (*(volatile uint32_t *)(RCC_BASE + 0x44))
#define SYSCFG_EXTICR4 (*(volatile uint32_t *)(SYSCFG_BASE + 0x14))
#define EXTI_IMR (*(volatile uint32_t *)(EXTI_BASE + 0x00))
#define EXTI_FTSR (*(volatile uint32_t *)(EXTI_BASE + 0x0C))
#define EXTI_PR (*(volatile uint32_t *)(EXTI_BASE + 0x14))
#define GPIOA_MODER  (*(volatile uint32_t *)(GPIOA_BASE + 0x00))
#define GPIOA_ODR    (*(volatile uint32_t *)(GPIOA_BASE + 0x14))
#define GPIOC_MODER (*(volatile uint32_t *)(GPIOC_BASE + 0x00))
#define GPIOC_PUPDR (*(volatile uint32_t *)(GPIOC_BASE + 0x0C))
#define GPIOC_IDR (*(volatile uint32_t *)(GPIOC_BASE + 0x10))
#define NVIC_ISER1  (*(volatile uint32_t *)0xE000E104)


void delay(volatile uint32_t count) {
    while(count--);
}

void EXTI15_10_IRQHandler(void) {
	if (EXTI_PR & (1 << 13)) {
		EXTI_PR |= (1 << 13);
		GPIOA_ODR ^= (1 << 5);
	}
}



int main(void)
{
	 // Enable clocks to GPIOA, GPIOC, SYSCFG
	    RCC_AHB1ENR |= (1 << 0);
	    RCC_AHB1ENR |= (1 << 2);
	    RCC_APB2ENR |= (1 << 14);

	    // Configure interrupt line and trigger condition
	    SYSCFG_EXTICR4 &= ~(0xF << 4);
	    SYSCFG_EXTICR4 |= (0x2 << 4);
	    EXTI_FTSR |= (1 << 13);
	    EXTI_IMR |= (1 << 13);
	    NVIC_ISER1 |= (1 << 8);

	    // Set PA5 as output (MODER bits 11:10 = 01)
	    GPIOA_MODER &= ~(3 << 10);
	    GPIOA_MODER |=  (1 << 10);

	    // Set PC13 as input and configure it properly
	    GPIOC_MODER |= (0 << 26);
	    GPIOC_MODER |= (0 << 27);
	    GPIOC_PUPDR &= ~(3 << 26);
	    GPIOC_PUPDR |= (1 << 26);

	    // PA5 low - LED off
        GPIOA_ODR &= ~(1 << 5);

	    // Infinite loop to prevent returning
	    for(;;) {
	    }
}
