/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

// LED 2 operates under PWM mode normally but turns off all the time when B1 is pressed
// Sends a message to terminal when B1 is pressed to inform current operation state

#include <stdint.h>

// Base Register addresses
#define RCC_BASE 0x40023800
#define GPIOA_BASE 0x40020000
#define GPIOC_BASE 0x40020800
#define SYSCFG_BASE 0x40013800
#define TIM2_BASE 0x40000000
#define SYST_BASE 0xE000E010
#define EXTI_BASE 0x40013C00
#define USART2_BASE 0x40004400

// Central Clocking Register Addresses
#define RCC_AHB1ENR  (*(volatile uint32_t *)(RCC_BASE + 0x30))
#define RCC_APB1ENR  (*(volatile uint32_t *)(RCC_BASE + 0x40))
#define RCC_APB2ENR  (*(volatile uint32_t *)(RCC_BASE + 0x44))

// GPIOA Addresses (LED2 pin)
#define GPIOA_MODER (*(volatile uint32_t *)(GPIOA_BASE + 0x00))
#define GPIOA_AFRL (*(volatile uint32_t *)(GPIOA_BASE + 0x20))
#define GPIOA_ODR  (*(volatile uint32_t *)(GPIOA_BASE + 0x14))

// GPIOC Addresses (B1 pin)
#define GPIOC_MODER (*(volatile uint32_t *)(GPIOC_BASE + 0x00))
#define GPIOC_PUPDR (*(volatile uint32_t *)(GPIOC_BASE + 0x0C))
#define GPIOC_IDR (*(volatile uint32_t *)(GPIOC_BASE + 0x10))

// Timer peripheral addresses
#define TIM2_CR1 (*(volatile uint32_t *)(TIM2_BASE + 0x00))
#define TIM2_CCMR1 (*(volatile uint32_t *)(TIM2_BASE + 0x18))
#define TIM2_CCER (*(volatile uint32_t *)(TIM2_BASE + 0x20))
#define TIM2_CNT (*(volatile uint32_t *)(TIM2_BASE + 0x24))
#define TIM2_PSC (*(volatile uint32_t *)(TIM2_BASE + 0x28))
#define TIM2_ARR (*(volatile uint32_t *)(TIM2_BASE + 0x2C))
#define TIM2_CCR1 (*(volatile uint32_t *)(TIM2_BASE + 0x34))

// CPU internal timer addresses
#define SYST_CSR (*(volatile uint32_t *)(SYST_BASE + 0x00))
#define SYST_RVR (*(volatile uint32_t *)(SYST_BASE + 0x04))
#define SYST_CVR (*(volatile uint32_t *)(SYST_BASE + 0x08))

// Interrupt config addresses
#define SYSCFG_EXTICR4 (*(volatile uint32_t *)(SYSCFG_BASE + 0x14))
#define EXTI_IMR (*(volatile uint32_t *)(EXTI_BASE + 0x00))
#define EXTI_FTSR (*(volatile uint32_t *)(EXTI_BASE + 0x0C))
#define EXTI_PR (*(volatile uint32_t *)(EXTI_BASE + 0x14))
#define NVIC_ISER1 (*(volatile uint32_t *)0xE000E104)

// UART addresses
#define USART2_SR (*(volatile uint32_t *)(USART2_BASE + 0x00))
#define USART2_DR (*(volatile uint32_t *)(USART2_BASE + 0x04))
#define USART2_BRR (*(volatile uint32_t *)(USART2_BASE + 0x08))
#define USART2_CR1 (*(volatile uint32_t *)(USART2_BASE + 0x0C))
#define USART2_CR2 (*(volatile uint32_t *)(USART2_BASE + 0x10))


// Control variables
volatile uint32_t tick = 0;
volatile uint8_t update_flag = 0;
volatile uint8_t up = 1;
volatile uint8_t pwm_mode = 1;

// Store displayed words into memory
char *word0 = "PWM Mode\n";
char *word1 = "Off Mode\n";

void SysTick_Handler(void) {
    tick++;
    update_flag = 1;  // signal main loop
}

void EXTI15_10_IRQHandler(void) {
	if (EXTI_PR & (1 << 13)) {
		EXTI_PR |= (1 << 13);
		if (pwm_mode) {
			int i = 0;
			while (word1[i] != '\0') {
				if ((USART2_SR & (1 << 7)) != 0) {
					USART2_DR = word1[i];
					i++;
				}
			}
			pwm_mode = 0;
		} else {
			int i = 0;
			while (word0[i] != '\0') {
				if ((USART2_SR & (1 << 7)) != 0) {
					USART2_DR = word0[i];
					i++;
				}
			}
			pwm_mode = 1;
		}
	}
}

int main(void)
{
	// Enable clocks to GPIOA, GPIOC, SYSConfig and TIM2
	RCC_AHB1ENR |= (1 << 0);
	RCC_AHB1ENR |= (1 << 2);
	RCC_APB1ENR |= (1 << 0);
	RCC_APB1ENR |= (1 << 17);
	RCC_APB2ENR |= (1 << 14);

	// Configure GPIOA Mode and setting Alternate Function
	GPIOA_MODER &= ~(3 << 10);
	GPIOA_MODER |= (2 << 10);
	GPIOA_AFRL &= ~(15 << 20);
	GPIOA_AFRL |= (1 << 20);
	GPIOA_MODER &= ~(15 << 4);
	GPIOA_MODER |= (10 << 4);
	GPIOA_AFRL &= ~(255 << 8);
	GPIOA_AFRL |= (119 << 8);

	// Set PC13 as input and configure it properly
	GPIOC_MODER |= (0 << 26);
	GPIOC_MODER |= (0 << 27);
	GPIOC_PUPDR &= ~(3 << 26);
	GPIOC_PUPDR |= (1 << 26);

	// Set PWM mode and output channel to 1
	TIM2_CCMR1 &= ~(7 << 4);
	TIM2_CCMR1 |= (6 << 4);
	TIM2_CCMR1 |= (1 << 3);

	// Configure interrupt line and trigger condition
	SYSCFG_EXTICR4 &= ~(0xF << 4);
	SYSCFG_EXTICR4 |= (0x2 << 4);
	EXTI_FTSR |= (1 << 13);
	EXTI_IMR |= (1 << 13);
	NVIC_ISER1 |= (1 << 8);

	// Set TIM2 frequency and clear counter
	TIM2_PSC = 15; //set as 16
	TIM2_ARR = 999; // set as 10^3
	TIM2_CNT = 0;
	TIM2_CCR1 = 0;

	// Configure SysTick and clear counter
	SYST_RVR = 159999;
	SYST_CVR = 0;

	// Configure USART2 Registers
	USART2_BRR = (8 << 4) | 11;
	USART2_CR1 &= ~(1 << 12);
	USART2_CR1 |= (1 << 2);
	USART2_CR1 |= (1 << 3);
	USART2_CR1 &= ~(1 << 10);
	USART2_CR2 &= ~(3 << 12);

	// Enable USART 2
	USART2_CR1 |= (1 << 13);

	// Enable TIM2 and SysTick and Channel 1 output
	SYST_CSR |= (1 << 0) | (1 << 1) | (1 << 2);
	TIM2_CR1 |= (1 << 0);
	TIM2_CCER |= (1 << 0);

    /* Loop forever */
	for(;;) {
		if (pwm_mode) {
			if (update_flag) {
				update_flag = 0;
				if (up) {
					if (TIM2_CCR1 + 10 >= 999) {
						TIM2_CCR1 = 999;
				        up = 0;
				    } else {
				        TIM2_CCR1 += 10;
				    }
				} else {
					if (TIM2_CCR1 <= 10) {
						TIM2_CCR1 = 0;
				        up = 1;
				    } else {
				        TIM2_CCR1 -= 10;
				    }
				}
			}
		} else {
			TIM2_CCR1 = 0;
		}
	}
}

