/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

// Define register base
#define RCC_BASE 0x40023800
#define USART2_BASE 0x40004400
#define GPIOA_BASE 0x40020000

// Define specific register addresses
#define RCC_APB1ENR  (*(volatile uint32_t *)(RCC_BASE + 0x40))
#define RCC_AHB1ENR (*(volatile uint32_t *)(RCC_BASE + 0x30))
#define USART2_SR (*(volatile uint32_t *)(USART2_BASE + 0x00))
#define USART2_DR (*(volatile uint32_t *)(USART2_BASE + 0x04))
#define USART2_BRR (*(volatile uint32_t *)(USART2_BASE + 0x08))
#define USART2_CR1 (*(volatile uint32_t *)(USART2_BASE + 0x0C))
#define USART2_CR2 (*(volatile uint32_t *)(USART2_BASE + 0x10))
#define GPIOA_MODER (*(volatile uint32_t *)(GPIOA_BASE + 0x00))
#define GPIOA_AFRL (*(volatile uint32_t *)(GPIOA_BASE + 0x20)) //AF7

int main(void)
{

	// Enable clocks to USART2 and GPIOA
	RCC_APB1ENR |= (1 << 17);
	RCC_AHB1ENR |= (1 << 0);

	// Configure mode for GPIOA
	GPIOA_MODER &= ~(15 << 4);
	GPIOA_MODER |= (10 << 4);
	GPIOA_AFRL &= ~(255 << 8);
	GPIOA_AFRL |= (119 << 8);

	// Configure USART2 Registers
	USART2_BRR = (8 << 4) | 11;
	USART2_CR1 &= ~(1 << 12);
	USART2_CR1 |= (1 << 2);
	USART2_CR1 |= (1 << 3);
	USART2_CR1 &= ~(1 << 10);
	USART2_CR2 &= ~(3 << 12);

	// Enable USART 2
	USART2_CR1 |= (1 << 13);

	char *word = "Hello World!";
	int i = 0;
	while (word[i] != '\0') {
		if ((USART2_SR & (1 << 7)) != 0) {
			USART2_DR = word[i];
			i++;
		}
	}

    /* Loop forever */
	for(;;) {
	}
}
